const QUESTIONS = [
  { id: 'q01', text: 'O seu personagem é do sexo masculino?' },
  { id: 'q02', text: 'O seu personagem tem cabelo?' },
  { id: 'q03', text: 'O seu personagem tem cabelo escuro (preto ou marrom)?' },
  { id: 'q04', text: 'O seu personagem tem cabelo loiro?' },
  { id: 'q05', text: 'O seu personagem tem cabelo ruivo?' },
  { id: 'q06', text: 'O seu personagem tem cabelo grisalho ou branco?' },
  { id: 'q07', text: 'O seu personagem tem cabelo comprido?' },
  { id: 'q08', text: 'O seu personagem tem cabelo cacheado ou encaracolado?' },
  { id: 'q09', text: 'O seu personagem tem barba?' },
  { id: 'q10', text: 'O seu personagem tem bigode?' },
  { id: 'q11', text: 'O seu personagem usa óculos?' },
  { id: 'q12', text: 'O seu personagem usa chapéu ou boné?' },
  { id: 'q13', text: 'O seu personagem tem olhos claros (azul ou verde)?' },
  { id: 'q14', text: 'O seu personagem tem nariz grande?' },
  { id: 'q15', text: 'O seu personagem tem orelhas grandes?' },
  { id: 'q16', text: 'O seu personagem está sorrindo?' },
  { id: 'q17', text: 'O seu personagem parece jovem (menos de 30 anos)?' },
  { id: 'q18', text: 'O seu personagem parece idoso (mais de 60 anos)?' },
  { id: 'q19', text: 'O seu personagem tem sardas ou marcas no rosto?' },
  { id: 'q20', text: 'O seu personagem tem sobrancelhas grossas ou marcantes?' },
  { id: 'q21', text: 'O seu personagem tem rosto redondo?' },
  { id: 'q22', text: 'O seu personagem tem a pele clara?' },
  { id: 'q23', text: 'O seu personagem tem a pele escura?' },
  { id: 'q24', text: 'O seu personagem tem brincos ou adornos visíveis?' },
  { id: 'q25', text: 'O seu personagem tem cabelo preso (rabo de cavalo, coque, trança)?' },
  { id: 'q26', text: 'O seu personagem está fazendo uma expressão marcante (careta, raiva, surpresa)?' },
  { id: 'q27', text: 'O seu personagem tem dentes à mostra?' },
  { id: 'q28', text: 'O seu personagem usa acessórios no pescoço (colar, gravata, lenço)?' },
  { id: 'q29', text: 'O seu personagem tem cabelo liso?' },
  { id: 'q30', text: 'O seu personagem parece de meia-idade (entre 30 e 60 anos)?' },
];
